trecauth.use-cookie=true
trecauth.refresh.domain=test.trecapps.com
trecauth.refresh.app=Trec-Apps-Message-Notify

#Storage Settings
trecauth.storage.strategy=Azure-key

trecauth.storage.account-name=${STORAGE_ACCOUNT_NAME}
trecauth.storage.account-key=${STORAGE_ACCOUNT_KEY}
trecauth.storage.blob-endpoint=${STORAGE_ACCOUNT_ENDPOINT}

# Set up Key Vault for use with JWT Auth token management
trecauth.jwt.key-storage.strategy=AKV-cred

trec.jwt.vault-name=trecappstestvault
trecauth.jwt.strategy=RSA
trecauth.jwt.rsa.public-key-name=trec-2022-pub
trecauth.jwt.rsa.private-key-name=trec-2022-priv-v8

trec.jwt.tenantId=${KV_TENANT}
trec.jwt.clientId=${KV_CLIENT_ID}
trec.jwt.clientSecret=${KV_CLIENT_SECRET}

ws.allowed.origins=https://test.trecapps.com

# For Field Encryption
trecauth.encryption.strategy=RSA
trecauth.encrypt.rsa.public-key-name=tc-field-pub
trecauth.encrypt.rsa.private-key-name=tc-field-priv

trecauth.encryptor.key-storage.strategy=AKV-cred
trec.encryptor.vault-name=trecappstestvault
trec.encryptor.tenantId=${KV_TENANT}
trec.encryptor.clientId=${KV_CLIENT_ID}
trec.encryptor.clientSecret=${KV_CLIENT_SECRET}

#Scheduling for Key Rotation
trecauth.rotate.do-rotate=true
trecauth.rotate.rotate-cron-schedule=0 0 2 ? * SUN *
trecauth.key.version-count=2

# Notification Consumerism
trecapps.message.producer.strategy=azure-service-bus-connection-string
trecapps.message.producer.queue=notify
trecapps.message.producer.connection=${TC_AZ_SERVICE_BUS_STR}

trecapps.notifications.consumer.strategy=az-service-bus-con-str
consumer.queue.name=notify
consumer.connection.str=${TC_AZ_SERVICE_BUS_STR}
