logging.level.root=info

spring.main.web-application-type=reactive

### Authentication Management ###

# Key Management
#trecauth.app=Message-Notify
trecauth.jwt.rsa.public-key-name=${TREC_PUBLIC_KEY}
trecauth.jwt.rsa.private-key-name=${TREC_PRIVATE_KEY}

# Set up Mongo Repository for Account storage
trecauth.account.repo.strategy=mongo-uri
trecauth.mongo.account.uri=${MONGO_URI}
trecauth.mongo.account.database=tc-accounts

# Cookie Names
trecauth.refresh.cookie-name=TC_REFRESH
trecauth.request.cookie-name=TC_REQUEST

# Key Management
trecauth.app=Message-Notify
trec.key.public=${TREC_PUBLIC_KEY}
trec.key.private=${TREC_PRIVATE_KEY}

# trecauth.refresh.domain=${REFRESH_DOMAIN}

### App Properties ###

spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# Message and Notification is global across TrecApps and so should be app agnostic at the TrecAuth level
trecauth.app.agnostic=true